theme = "catppuccin_latte"

[editor]
auto-save = true
rulers = [80, 120]
cursorline = true
cursorcolumn = true
bufferline = "always"
color-modes = true

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[editor.soft-wrap]
enable = true
# wrap-at-text-width = true
wrap-indicator = "↩ "

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"    # Non Breaking SPace
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)
### 

[editor.statusline]
left = [ "mode", "spinner", "read-only-indicator", "file-modification-indicator" ]
center = [ "file-name", "separator", "version-control", "separator" ]
right = [ "diagnostics", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.statusline.mode]
insert = "INSERT"
normal = "NORMAL"
select = "SELECT"
